// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @blind-push/blind-peer-request-block
const encoding0 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.index)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.index)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      key: r0,
      index: r1
    }
  }
}

// @blind-push/blind-peer-request-destination
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.buffer.preencode(state, m.discoveryKey)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.buffer.encode(state, m.discoveryKey)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      discoveryKey: r1
    }
  }
}

// @blind-push/blind-peer-request.block
const encoding2_0 = c.frame(encoding0)
// @blind-push/blind-peer-request.destination
const encoding2_1 = c.frame(encoding1)

// @blind-push/blind-peer-request
const encoding2 = {
  preencode(state, m) {
    encoding2_0.preencode(state, m.block)
    encoding2_1.preencode(state, m.destination)
  },
  encode(state, m) {
    encoding2_0.encode(state, m.block)
    encoding2_1.encode(state, m.destination)
  },
  decode(state) {
    const r0 = encoding2_0.decode(state)
    const r1 = encoding2_1.decode(state)

    return {
      block: r0,
      destination: r1
    }
  }
}

// @blind-push/proof-payload
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.buffer.preencode(state, m.proof)
    state.end++ // max flag is 1 so always one byte

    if (m.extra) c.buffer.preencode(state, m.extra)
  },
  encode(state, m) {
    const flags = m.extra ? 1 : 0

    c.uint.encode(state, m.version)
    c.buffer.encode(state, m.proof)
    c.uint.encode(state, flags)

    if (m.extra) c.buffer.encode(state, m.extra)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      proof: r1,
      extra: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @blind-push/push-payload
const encoding4 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.payload)
    c.buffer.preencode(state, m.discoveryKey)
  },
  encode(state, m) {
    c.buffer.encode(state, m.payload)
    c.buffer.encode(state, m.discoveryKey)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      payload: r0,
      discoveryKey: r1
    }
  }
}

// @blind-push/gateway-forward-request.payload
const encoding5_0 = c.frame(encoding4)

// @blind-push/gateway-forward-request
const encoding5 = {
  preencode(state, m) {
    encoding5_0.preencode(state, m.payload)
    state.end++ // max flag is 1 so always one byte

    if (m.appId) c.string.preencode(state, m.appId)
  },
  encode(state, m) {
    const flags = m.appId ? 1 : 0

    encoding5_0.encode(state, m.payload)
    c.uint.encode(state, flags)

    if (m.appId) c.string.encode(state, m.appId)
  },
  decode(state) {
    const r0 = encoding5_0.decode(state)
    const flags = c.uint.decode(state)

    return {
      payload: r0,
      appId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@blind-push/blind-peer-request-block':
      return encoding0
    case '@blind-push/blind-peer-request-destination':
      return encoding1
    case '@blind-push/blind-peer-request':
      return encoding2
    case '@blind-push/proof-payload':
      return encoding3
    case '@blind-push/push-payload':
      return encoding4
    case '@blind-push/gateway-forward-request':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
